import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import Sidebar from '@/components/Sidebar'
import Topbar from '@/components/Topbar'
import Player from '@/components/Player'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased dark',
          fontSans.variable
        )}
      >
        <div className="flex flex-row">
          <Sidebar />
          <div className="w-full h-full">
            <Topbar />
            {children}
          </div>
        </div>
        <Player name="Name of Song" extra="Name of the Artist" />
      </body>
    </html>
  )
}
