import React from 'react'
import Script from "next/script"
import Head from 'next/head'
import Image from 'next/image'
import { MusicPlayback } from './MusicPlayback'
import { SideBar } from './SideNavBar'
import { TopBar } from './TopBar'

export default function Layout({ children, title = 'PiTunes' }) {
  return (
    <div className='dark'>
      <Script data-ad-client="ca-pub-5588726027217390" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></Script>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-white dark:bg-dark h-screen'>
        <div className='flex h-[88vh]'>
          <SideBar/>
          <div className='w-full h-full relative overflow-y-scroll'>
            <TopBar/>
            {children}
          </div>
        </div>
        <MusicPlayback SongName='Name of Song' ArtistName='Name of the Artist'/>
      </div>
    </div>
  )
}