import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { MusicPlayback } from './MusicPlayback'
import { SideBar } from './SideNavBar'
import { TopBar } from './TopBar'

export function Layout({ children }) {
  return (
    <div className='dark'>
      <Head>
        <title>PiTunes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-white dark:bg-dark h-screen'>
        <div className='flex h-[88vh]'>
          <SideBar/>
          <div className='w-full h-full relative overflow-y-scroll'>
            <TopBar/>
            {children}
          </div>
        </div>
        <MusicPlayback SongName='Name of Song' ArtistName='Name of the Artist'/>
      </div>
    </div>
  )
}